### PR TITLE
fix: fix different import action

### PR DESCRIPTION
**Pull request by Zxilly**
This will keep legacy usage like `const MongooseAdapter = require('casbin-mongoose-adapter');`

### CODE REVIEW

**Comment by Sefriol** [comment]
lgtm

**Review by Sefriol — APPROVED** [review]

**Comment by hsluoyz** [comment]
@Zxilly why do this PR? Maybe we can setup semantic-release first, then test it with this PR's merge.

**Comment by Zxilly** [comment]
@hsluoyz During the refactoring to Typescript, the import action was changed.
Yes, we can merge this after the auto release setup.

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/node-casbin/mongoose-adapter/pull/37

**Pull request closed without merging**
