### PR TITLE
Upgrade casbin version to v5.0.7

### PR DESCRIPTION
**Pull request by StefanoPastore**
Align `casbin` version to the latest one [v5.0.7](https://github.com/casbin/node-casbin/releases/tag/v5.0.7).

### CODE REVIEW

**Comment by hsluoyz** [comment]
@StefanoPastore please fix CI.

**Comment by hsluoyz** [comment]
@StefanoPastore and fix conflicts.

**Comment by StefanoPastore** [comment]
@hsluoyz I resolved confilcts but the CI errors i cannot reproduce them. In fact now CI is working properly 🤷‍♂️

**Comment by hsluoyz** [comment]
lgtm

**Comment by hsluoyz** [comment]
@nodece @zhmushan please release a new version.

**Pull request merged**
