### PR TITLE
fix: no longer support legacy require

### PR DESCRIPTION
**Pull request by Zxilly**
Signed-off-by: Zxilly <zhouxinyu1001@gmail.com>

resolve: #42

### CODE REVIEW

**Comment by Zxilly** [comment]
I think there's no way to support

```js
const xxx = require('xxx')
```

and

```js
const { xxx } = require('xxx')
```

at the same time. So I give up the former.

**Comment by Zxilly** [comment]
Seems coverall server is down now. I will rerun jobs tomorrow.
image

**Comment by hsluoyz** [comment]
@fdionisi plz review.

**Review by fdionisi — APPROVED** [review]
@Zxilly @hsluoyz LGTM! Tried locally and works like a charm. Thanks for taking the time to look into this.

I won't review `.github/workflows/main.yml` nor `.releaserc.json`, though. They are more related to your release process than the issues I pointed out.

**Review by Sefriol — APPROVED** [review]

**Comment by hsluoyz** [comment]
@Zxilly plz setup semantic-bot to check PR title:

image

**Pull request merged**
