### PR TITLE
fix!: Field name 'p_type' to 'ptype'

### PR DESCRIPTION
**Pull request by Shivansh-yadav13**
- #55 
- breaking change

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 fix:

image

**Comment by nodece** [comment]
@Shivansh-yadav13 Could you add these changes to README.md？

**Comment by Shivansh-yadav13** [comment]
ok

**Comment by Shivansh-yadav13** [comment]
@nodece but the changes are not released.

**Comment by nodece** [comment]
Use `fix: add xxx to README.md`, this commit will trigger a release.

**Comment by Shivansh-yadav13** [comment]
ok I will also add an example of schema so it's clear about the change,

**Comment by hsluoyz** [comment]
@nodece plz don't merge the PR without resolving all errors. The release won't fail if all errors have been properly handled.

image

**Comment by Shivansh-yadav13** [comment]
but sir I did fixed it.

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 then where is the v5 release?

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 then where is the v5 release?

**Pull request merged**
