### PR TITLE
feat: upgrade mongoose to 8.1.0 and casbin to 5.28.0

### PR DESCRIPTION
**Pull request by emanuelet**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@emanuelet plz fix CI errors:

image

**Comment by emanuelet** [comment]
I runned the tests locally and I they passed correctly. Any idea why they would timeout on CI ?

**Comment by hsluoyz** [comment]
@emanuelet you may need to fix the CI script

**Comment by hsluoyz** [comment]
@emanuelet still error

**Comment by hsluoyz** [comment]
@emanuelet the CI has failed: https://github.com/node-casbin/mongoose-adapter/actions/runs/7653378578/job/20855198639 , can you please fix it?

image

**Pull request merged**
