### PR TITLE
Feature casbin 4

### PR DESCRIPTION
**Pull request by Sefriol**
- Update all tests to take into account async casbin 4
- Change dependancies into more up to date versions
- Add `prepare-commit-msg` hook, so it's more in line with other casbin packages
- Minor improvements to the test environtment:
    * `deleteUser` and `deleteRole` tests
    * Change all test to take into account async casbin 4
    * Switch deprecated mocha.opts into .mocharc.js files
    * Deprecated `isparta` changed to up to date `nyc`

### CODE REVIEW

**Comment by hsluoyz** [comment]
@ghaiklor @nodece please review.

**Comment by nodece** [comment]
@hsluoyz lgtm

**Comment by nodece** [comment]
@Sefriol 'casbin' should as peer dependencies and devDependencies.

**Comment by hsluoyz** [comment]
@nodece please review. If you approve it, please merge and release new version.

**Pull request merged**
